services:
  - type: web
    name: bmi-cms-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: BMI_MCMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: bmi-cms-api
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: bmi-cms-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: bmi-cms-db
    databaseName: bmi_cms_db
    user: bmi_user
    plan: free
    postgresMajorVersion: "16"
